[toolchain]
channel = "nightly"
targets = [
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "aarch64-apple-darwin",
]
profile = "default"
components = ["rustc", "cargo", "rustfmt", "clippy"]
